apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: nestjs-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
  labels:
    app: nestjs-app
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
