apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-load-balancer
  labels:
    app: nestjs-app
spec:
  type: LoadBalancer
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
